sudo: required
language: node_js
node_js:
  - node
services:
  - docker
before_install:
  - docker build -t react-truncate-markup .
  - docker images
install:
  - yarn
script:
  - yarn test:ci
notifications:
  email: false
branches:
  only: master
